#!/usr/bin/python

def agent_barracudamini_arguments(params, hostname, ipaddress):
	args = ''
	args += " --host " + quote_shell_string("%s" % (hostname))
	args += " --username " + quote_shell_string(params["username"])
	args += " --password " + quote_shell_string(params["password"])

	return args

special_agent_info['barracudamini'] = agent_barracudamini_arguments