#!/usr/bin/python

check_default_levels["cisco_currlinerate"] = "cisco_currlinerate_default_levels"

factory_settings["cisco_currlinerate_default_levels"] = {
        "download" : (14000000, 10000000),
        "upload" : (2000000, 1500000)
}

def inventory_cisco_currlinerate (info):
        inventory = []

        for upload, download in info[0]:
                inventory.append( ("Cisco Current Line Rate", {}) )

        return inventory

def check_cisco_currlinerate (item, params, info):
        if len(info) != 1:
                return(3, "UNKNOWN - Invalid output from Agent")

        moduleinfo = {}
        perfdata = []
        severity = "OK"
        rc = 0
        infotext = "Current Line Rate"

        # Get warn/crit values
        downloadparams = params.get("download")
        if downloadparams == None:
                downloadwarn, downloadcrit = None, None
        else:
                downloadwarn, downloadcrit = downloadparams

        uploadparams = params.get("upload")
        if uploadparams == None:
                uploadwarn, uploadcrit = None, None
        else:
                uploadwarn, uploadcrit = uploadparams

        for download, upload in info[0]:
                # compare download measurement value against warn, crit thresholds
                if downloadcrit and downloadwarn:
                        if saveint(download) <= downloadcrit:
                                severity = "CRITICAL"
                                rc = 2
                                infotext += " download: %s bps (!!)," % (download)
                        elif saveint(download) <= downloadwarn:
                                severity = "WARNING"
                                rc = 1
                                infotext += " download: %s bps (!)," % (download)
                        else:
                                infotext += " download: %s bps," % (download)
                else:
                        infotext += " download: %s bps," % (download)

                # compare upload measurement value against warn, crit thresholds
                if uploadcrit and uploadwarn:
                        if saveint(upload) <= uploadcrit:
                                severity = "CRITICAL"
                                rc = 2
                                infotext += " upload: %s bps (!!)," % (upload)
                        elif saveint(upload) <= uploadwarn:
                                severity = "WARNING"
                                rc = 1
                                infotext += " upload: %s bps (!)," % (upload)
                        else:
                                infotext += " upload: %s bps," % (upload)
                else:
                        infotext += " upload: %s bps," % (upload)

                perfdata = [ ( "download", saveint(download), downloadwarn, downloadcrit ),
                                ( "upload", saveint(upload), uploadwarn, uploadcrit ) ]

                output = severity + " - " + infotext
                return (rc, output, perfdata)
        return (3, "UNKNOWN - item not found in snmp data")

check_info['cisco_currlinerate'] = \
          (check_cisco_currlinerate, "%s", 1, inventory_cisco_currlinerate)


snmp_info['cisco_currlinerate'] = [ 
        ( ".1.3.6.1.2.1.10.94.1.1",[
                4, # "download"
                5, # "upload"
                ]
        ),
]

snmp_scan_functions["cisco_currlinerate"] = \
lambda oid: "Cisco IOS" in oid(".1.3.6.1.2.1.1.1.0")
