#!/usr/bin/python

check_default_levels["cisco_attenuation"] = "cisco_attenuation_default_levels"

factory_settings["cisco_attenuation_default_levels"] = {
        "download" : (14, 16),
        "upload" : (24, 26)
}

def parse_cisco_attenuation(info):
    from collections import defaultdict
    download, upload = info
    downloads = defaultdict(list)
    for x in download:
        downloads["datt"].append(x[1])

    uploads = defaultdict(list)
    for y in upload:
	    uploads["uatt"].append(y[1])

    att = []
    att.append( ( downloads, uploads ) )
    return att

def inventory_cisco_attenuation (info):
        inventory = []

        for upload, download in info[1]:
                inventory.append( ("Cisco Attenuation", "cisco_attenuation_default_levels") )

        return inventory

def check_cisco_attenuation (item, params, info):
        if len(info[0]) != 1:
                return(3, "UNKNOWN - Invalid output from Agent")

        moduleinfo = {}
        perfdata = []
        severity = "OK"
        rc = 0
        infotext = "Attenuation"

        # Get warn/crit values
        downloadparams = params.get("download")
        if downloadparams == None:
                downloadwarn, downloadcrit = None, None
        else:
                downloadwarn, downloadcrit = downloadparams

        uploadparams = params.get("upload")
        if uploadparams == None:
                uploadwarn, uploadcrit = None, None
        else:
                uploadwarn, uploadcrit = uploadparams
                
	att = parse_cisco_attenuation(info)

        for download, upload in att:
                adownload = int(download['datt'][0])*0.1
                # compare download measurement value against warn, crit thresholds
                if downloadcrit and downloadwarn:
                        if saveint(adownload) >= downloadcrit:
                                severity = "CRITICAL"
                                rc = 2
                                infotext += " download: %s dBm (!!)," % (adownload)
                        elif saveint(adownload) >= downloadwarn:
                                severity = "WARNING"
                                rc = 1
                                infotext += " download: %s dBm (!)," % (adownload)
                        else:
                                infotext += " download: %s dBm," % (adownload)
                else:
                        infotext += " download: %s dBm," % (adownload)

                aupload = int(upload['uatt'][0])*0.1
                # compare upload measurement value against warn, crit thresholds
                if uploadcrit and uploadwarn:
                        if saveint(aupload) >= uploadcrit:
                                severity = "CRITICAL"
                                rc = 2
                                infotext += " upload: %s dBm (!!)," % (aupload)
                        elif saveint(aupload) >= uploadwarn:
                                severity = "WARNING"
                                rc = 1
                                infotext += " upload: %s dBm (!)," % (aupload)
                        else:
                                infotext += " upload: %s dBm," % (aupload)
                else:
                        infotext += " upload: %s dBm," % (aupload)

                perfdata = [ ( "download", saveint(adownload), downloadwarn, downloadcrit ),
                                ( "upload", saveint(aupload), uploadwarn, uploadcrit ) ]

                output = severity + " - " + infotext
                return (rc, output, perfdata)
        return (3, "UNKNOWN - item not found in snmp data")

check_info['cisco_attenuation'] = \
          (check_cisco_attenuation, "%s", 1, inventory_cisco_attenuation)

snmp_info['cisco_attenuation'] = [ 
        ( ".1.3.6.1.2.1.10.94.1.1.2.1.5", [OID_END,12] ),
        ( ".1.3.6.1.2.1.10.94.1.1.3.1.5", [OID_END,12] ),]

snmp_scan_functions["cisco_attenuation"] = \
lambda oid: "Cisco IOS" in oid(".1.3.6.1.2.1.1.1.0")
