#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 2 -*-

check_default_levels["asterisk_peers"] = "asterisk_peers_default_levels"

factory_settings["asterisk_peers_default_levels"] = {
  "asteriskPeerLatency" : (1500, 2000)
}

def inventory_asterisk_peers(info):
  for line in info:
    host = line[0]
    yield host, None

def check_asterisk_peers(item, params, info):

  # Get warn/crit values
  asteriskPeerLatencyparams = params.get("asteriskPeerLatency")
  if asteriskPeerLatencyparams == None:
    asteriskPeerLatencywarn, asteriskPeerLatencycrit = None, None
  else:
    asteriskPeerLatencywarn, asteriskPeerLatencycrit = asteriskPeerLatencyparams

  for line in info:
    if line[0] == item:
      perfdata = [ ( "asteriskPeerLatency", saveint(line[4]), asteriskPeerLatencywarn, asteriskPeerLatencycrit ) ]
      if line[3] == "OK":
        return (0, "State is %s, latency is %dms" % (line[3], saveint(line[4])), perfdata)
      else:
        return (2, "State is %s (!!)" % line[3], perfdata)

  return (3, "UNKNOWN - item not found in snmp data")

check_info['asterisk_peers'] = (check_asterisk_peers, "Asterisk peer %s", 1, inventory_asterisk_peers)